# fly.toml app configuration file generated for rafacvgpt on 2023-06-19T09:47:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rafacvgpt"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
